name: 'Deploy to Railway with Service ID'
description: 'A Github Action to deploy to Railway with a specified Service ID'

branding:
  icon: check
  color: gray-dark

inputs:
  railway_token:
    description: 'The Railway Token'
    required: false
  railway_service:
    description: 'the Railway Service identifier against which the deployment should be run'
    required: false

outputs:
  status:
    description: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.railway_token }}
    - ${{ inputs.railway_service }}
